#
# Deployments
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        env:
        - name: MONGO_INITDB_DATABASE
          value: admin
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-express
  name: mongo-express
spec:
  selector:
    matchLabels:
      app: mongo-express
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          value: "mongo"
        - name: ME_CONFIG_MONGODB_AUTH_DATABASE
          value: admin
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          value: "admin"
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          value: "admin"
        #- name: ME_CONFIG_BASICAUTH_USERNAME
        #  value: "guest"
        #- name: ME_CONFIG_BASICAUTH_PASSWORD
        #  value: "guest"
        image: mongo-express:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          protocol: TCP
      restartPolicy: Always
---
#
# Services
#
kind: Service
apiVersion: v1
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
    - name: mongo-port
      port: 27017
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: mongo-express
spec:
  selector:
    app: mongo-express
  ports:
    - name: mongo-express-port
      port: 8081
      nodePort: 30081
  type: NodePort
  #type: ClusterIP
